### ISSUE TITLE
rake not working?

### ISSUE THREAD

**Issue by kjorg50** [scalableinternetservicesarchive/LaPlaya#17]
My `rake` command is not working since I checked out the new master branch. For some reason any rake command I try gives me this error. Anyone else experiencing this issue?

```
☁  LaPlaya [master] rake -T
rake aborted!
ArgumentError: Invalid source: nil
/home/kylejorgensen/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/source_list.rb:72:in `source_list_for'
/home/kylejorgensen/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/source_list.rb:36:in `get'
/home/kylejorgensen/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/definition.rb:525:in `block in converge_locked_specs'
/home/kylejorgensen/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/definition.rb:524:in `converge_locked_specs'
/home/kylejorgensen/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/definition.rb:190:in `resolve'
/home/kylejorgensen/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/definition.rb:132:in `specs'
/home/kylejorgensen/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/definition.rb:177:in `specs_for'
/home/kylejorgensen/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/definition.rb:166:in `requested_specs'
/home/kylejorgensen/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/environment.rb:18:in `requested_specs'
/home/kylejorgensen/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:13:in `setup'
/home/kylejorgensen/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler.rb:121:in `setup'
/home/kylejorgensen/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/setup.rb:7:in `<top (required)>'
/home/kylejorgensen/cs/LaPlaya/config/boot.rb:4:in `<top (required)>'
/home/kylejorgensen/cs/LaPlaya/config/application.rb:1:in `<top (required)>'
/home/kylejorgensen/cs/LaPlaya/Rakefile:4:in `<top (required)>'
/home/kylejorgensen/.rvm/gems/ruby-2.1.3@LaPlaya/bin/ruby_executable_hooks:15:in `eval'
/home/kylejorgensen/.rvm/gems/ruby-2.1.3@LaPlaya/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by jhenkens** [comment]
Nope. If you are using rvm, try the following:

rvm gem set empty
rm Gemfile.lock
gem install bundler
bundle update

–––––––––––––––––
Johan Henkens
johan@henkens.com

**Comment by kjorg50** [comment]
That magically fixed it. Thanks!
